name: Deploy goals API

on:
  workflow_dispatch:

jobs:
  pipeline:
    uses: IDEMSInternational/parenttext-goals-webhooks/.github/workflows/deploy.yml@325c62b556b746330ced126c581d000922e12d25
    secrets:
      credentials: ${{ secrets.GCP_CREDENTIALS }}
    with:
      image: ${{ vars.GOALS_API_IMAGE }}
      region: ${{ vars.GCP_REGION }}
      service_env: ${{ vars.GCP_SERVICE_ENV }}
      service_name: ${{ vars.GCP_SERVICE_NAME }}
